services:
  - type: web
    name: my-python-app
    env: docker
    runtime: python3.10
    pythonVersion: 3.10.12  # Ensure this matches the version you're targeting
    buildCommand: |
      docker build -t chingyi497/my-python-app .
      apt-get update && apt-get install -y libffi-dev libjpeg-dev zlib1g-dev
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt --no-cache-dir
    startCommand: docker run -p 2000:2000 chingyi497/my-python-app
